### ISSUE TITLE
export to archimate contains no applications

### ISSUE THREAD

**Issue by rietkraag** [hsleisink/landscape#1]
hello Hugo, i've installed landscape 0.6 today. Everything works fine; only exporting to archimate is incomplete. it misses applications. Exporting to xml contains everything.

**Comment by rietkraag** [comment]
I have creatief 4 applications in landscape, some hardware and some connecties. When I export it then the applications do nog appear in Archi. Ik opened the file and they are missing. Exporting to XML works as expected.

**Comment by rietkraag** [comment]
Creatief moet created zijn ☺️

**Comment by rietkraag** [comment]
Hugo,

To make it clear I have created the following in Landscape:

![screenshot-2018-4-27 overview - application landscape database](https://user-images.githubusercontent.com/19517423/39371350-bcedb778-4a41-11e8-923b-9a5395769f3c.png)

Opening the export file results in an error:
![knipsel](https://user-images.githubusercontent.com/19517423/39371441-00e4bb7a-4a42-11e8-9402-a073d18aea2d.PNG)

XML contains Application1

XML
`<?xml version="1.0" encoding="utf-8"?>
<output>
<applications>
<application id="56">
<organisation_id>3</organisation_id>
<name>Application1</name>
<type></type>
<description></description>
<owner_id></owner_id>
<confidentiality>0</confidentiality>
<availability>0</availability>
<integrity>0</integrity>
<location>0</location>
</application>
</applications>
<business>
<entity id="49">
<organisation_id>3</organisation_id>
<name>User1</name>
<description></description>
</entity>
</business>
<data_collections>
</data_collections>
<hardware>
<device id="22">
<organisation_id>3</organisation_id>
<name>Hardware1</name>
<os>OS1</os>
<description></description>
</device>
</hardware>
<connections>
</connections>
<file_operations>
</file_operations>
<app_usedby>
<usage id="35">
<application_id>56</application_id>
<business_id>49</business_id>
<input>Question1</input>
<description></description>
</usage>
</app_usedby>
<data_usedby>
</data_usedby>
<runsat>
<item id="43">
<application_id>56</application_id>
<hardware_id>22</hardware_id>
</item>
</runsat>
<processings>
</processings>
<usages>
</usages>
</output>
`

Archimate
`<?xml version="1.0" encoding="utf-8"?>
<archimate:model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:archimate="http://www.archimatetool.com/archimate" name="Application landscape" id="landscape" version="2.6.0">
<folder name="Technology" id="technology" type="technology">
<element xsi:type="archimate:Device" id="hdw_22" name="Hardware1">
<property key="OS" value="OS1"></property>
</element>
</folder>
<folder name="Relations" id="relations" type="relations">
<element xsi:type="archimate:UsedByRelationship" id="use_a35" source="app_56" target="bus_49">
<property key="Input" value="Question1"></property>
</element>
<element xsi:type="archimate:RealisationRelationship" id="run_43" source="hdw_22" target="app_56"></element>
</folder>
<folder name="Views" id="views" type="diagrams">
<element xsi:type="archimate:ArchimateDiagramModel" id="view" name="Application landscape"></element>
</folder>
</archimate:model>
`
Kind regards,
Roel

**Comment by hsleisink** [comment]
I think I found what causes your issue. If you redownload controllers/export.php from github, you should get a working export.

**Comment by rietkraag** [comment]
Thanks for the quick response. It's working now :-)

<img width="271" alt="knipsel" src="https://user-images.githubusercontent.com/19517423/39410473-00f69f4e-4bf9-11e8-9505-ca33d31da31d.PNG">

**Comment by hsleisink** [comment]
That’s good to hear. If you have any feedback about the application itself, please let me know. I really like to hear what people think of it.
